# Site settings
author: Kayla Cross
title: Kayla Cross
header-img: img/new-header.png
email: kac288@georgetown.edu
copyright_name: Kayla Cross
description: > # this means to ignore newlines until "baseurl:"
  (mis)adventures in coding and writing
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username:
github_username:  crosskayla
linkedin_username: kayla-cross-09a455b1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
